server:
  port: 8511

spring:
  application:
    name: service-product
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 54.225.96.210:8848 #TODO
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #TODO
    url: jdbc:mysql://54.225.96.210:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml